# CI: Test (all branches except main)
# This workflow runs tests on all branches except main.

name: CI Test (all branches except main)

on:
  push:
    branches-ignore:
      - main

jobs:
  test-only:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DB: ${{ vars.MONGODB_DB }}
      API_SERVER: ${{ vars.API_SERVER }}
      RECIPE_API: ${{ vars.RECIPE_API }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and start containers
        run: |
          docker compose up --build -d
      - name: Wait for app to start
        run: sleep 5
      - name: Run tests in app container
        run: |
          docker exec shoppinglist-app npm run test
      - name: Stop and clean up containers
        if: always()
        run: |
          docker compose down -v
