name: Run tests on push and pull requests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DB: ${{ vars.MONGODB_DB }}
      API_SERVER: ${{ vars.API_SERVER }}
      RECIPE_API: ${{ vars.RECIPE_API }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and start containers
        run: |
          docker compose up --build -d
      - name: Wait for app to be ready
        run: |
          for i in {1..30}; do
            docker exec shoppinglist-app sh -c 'curl -sf "$API_SERVER/"' && \
            echo "App server is up" && break
            sleep 2
          done
      - name: Run tests in app container
        run: |
          docker exec shoppinglist-app npm test
      - name: Stop and clean up containers
        if: always()
        run: |
          docker compose down -v
      - name: Upload coverage to Coveralls
        run: cat ./coverage/lcov.info | npx coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
