name: Run tests on push and pull requests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass
      MONGODB_URI: mongodb://testuser:testpass@shoppinglist-mongo:27017/shoppinglistdb?authSource=admin
      MONGODB_DB: shoppinglistdb
      API_SERVER: http://shoppinglist-app:3000
      RECIPE_API: http://www.themealdb.com/api/json/v1/1/search.php?s=
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and start containers
        run: |
          docker compose up --build -d
      - name: Wait for app to be ready
        run: |
          for i in {1..30}; do
            docker exec shoppinglist-app nc -z shoppinglist-mongo 27017 && \
            docker exec shoppinglist-app nc -z shoppinglist-app 3000 && \
            echo "App and MongoDB are up" && break
            sleep 2
          done
      - name: Run tests in app container
        run: |
          docker exec shoppinglist-app npm test
      - name: Stop and clean up containers
        if: always()
        run: |
          docker compose down -v
      - name: Upload coverage to Coveralls
        run: cat ./coverage/lcov.info | npx coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
